name: CitizensModels
version: '${version}'
main: top.mrxiaom.citizensmodels.CitizensModels
api-version: 1.13
folia-supported: true
depend:
  - Citizens
softdepend:
  - PlaceholderAPI
  - ModelEngine
  - BetterModel
authors: [ MrXiaoM ]
# PluginBase Libraries ${libraries_config}
commands:
  citizensmodels:
    description: 'The main command of CitizensModels'
    aliases: [ npcmodels, npcmodel, npcm, cm ]
